### PR TITLE
Make generated factory request null safe adapters.

### LINKED ISSUE #25: Generated JsonAdapter.Factory doesn't handle nulls
If a class that uses the generated `typeAdapterFactory` ends up having a `null` value in the JSON, parsing fails with:

```
com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was NULL at path $.data
at com.squareup.moshi.JsonReader.beginObject(JsonReader.java:383)
at io.github.ktchernov.moshiautovaluebug.AutoValue_TestClassA_TestClassB$AutoValue_TestClassBJsonAdapter.fromJson(AutoValue_TestClassA_TestClassB.java:39)
at io.github.ktchernov.moshiautovaluebug.AutoValue_TestClassA_TestClassB$AutoValue_TestClassBJsonAdapter.fromJson(AutoValue_TestClassA_TestClassB.java:32)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:183)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:144)
at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
at io.github.ktchernov.moshiautovaluebug.MoshiAutoValueTest.parseWithNull(MoshiAutoValueTest.java:33)
....
```

What should happen, is that `null` should be parsed as a `null` object.

I've created a gist with a sample class and a unit test here: https://gist.github.com/ktchernov/cd3520cebf8aa56214b5155a648d38d4

The first unit test `parseValid()` passes as expected, the second test `parseWithNull()` fails with the above exception.

### PR DESCRIPTION
**Pull request by serj-lotutovici**
- Introduces nullSafe() element to MoshiAdapterFactory annotation with a
  default value as false (to respect current usages of the library).
- Generated MoshiAdapterFactory will request null safe adapters if
  requested by the user.
- Some minor cleanups (reduced amount of spec and type lookups)

Closes #25 

**Reasoning for extra meta data in the annotation: ** AutoValue by default enforces null safety and users have to explicitly specify that a value is allowed to be null. I reasoned that current users of the library may not expect nulls in their value classes thus such a change could break expected behaviour. This will force users to make a conscious decision wether or not they need their adapters to return null.

### CODE REVIEW

**Comment by serj-lotutovici** [comment]
Btw, while writing this something didn't feel right. The `Processor#process()` method gets all classes annotated with `@MoshiAdapterFactory` and generates the same exact implementation but under the different name. Should we restrict that to only one class?

**Comment by rharter** [comment]
There was some discussion about how to approach the `@MoshiAdapterFactory` in #40, which covers the challenges of picking one.  Who knows why someone might do that, perhaps they are a large team on a large codebase and a developer doesn't know there is already one there?  I would argue that is a user issue, not something the library should enforce, as there's technically nothing wrong with having multiples.

File: auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiAdapterFactoryProcessor.java [hunk 1]
```diff
@@ -53,6 +53,18 @@
  */
 @AutoService(Processor.class)
 public class AutoValueMoshiAdapterFactoryProcessor extends AbstractProcessor {
+  public static final ParameterSpec TYPE_SPEC = ParameterSpec.builder(Type.class, "type").build();
```
Comment (rharter) [inline auto-value-moshi/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiAdapterFactoryProcessor.java]: nit: These should be private.

**Review by rharter — CHANGES_REQUESTED** [review]

**Comment by serj-lotutovici** [comment]
@rharter changes done. Travis build failed, but seams because of a network error.

**Comment by serj-lotutovici** [comment]
@rharter / @hzsweers any thought regarding this one?

**Review by rharter — APPROVED** [review]

**Comment by rharter** [comment]
Sorry, got lost in thinking it wasn't updated because of (my) red X.  Looks good to me.

**Comment by ZacSweers** [comment]
Not totally sure I agree with this, mostly because it might either be redundant or you forfeit granularity (vs. just tacking on nullsafe() to the adapter you return in the static jsonAdapter() methods. I don't think we'd use it anyway, even if we did want nullsafe on some adapters
