### PR TITLE
Caches delegate JsonAdapters in generated JsonAdapter. Fixes #6

### LINKED ISSUE #6: Cache delegate JsonAdapter instances in generated JsonAdapter
Something like:

``` java
private final JsonAdapter<String> bar;
private final JsonAdapter<Map<String, String>> baz;

FooJsonAdapter(Moshi moshi) {
  bar = moshi.adapter(String.class);
  baz = moshi.adapter(Types.newParameterizedType(Map.class, String.class, String.class));
}
```

This saves having to look them up for every serialization/deserialization and also saves the creation of the parameterized type instance for lookup when generic types are used.

It also moves configuration exceptions to happen when the user looks up an adapter for their type rather than when serialization actually happens.

### PR DESCRIPTION
**Pull request by rharter**

### CODE REVIEW

File: src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java [hunk 1]
```diff
@@ -180,28 +195,43 @@ public TypeSpec createTypeAdapter(ClassName className, ClassName autoValueClassN
     ClassName jsonAdapter = ClassName.get(JsonAdapter.class);
     TypeName typeAdapterClass = ParameterizedTypeName.get(jsonAdapter, autoValueClassName);
 
+    ImmutableMap<Property, FieldSpec> adapters = createFields(properties);
     FieldSpec moshiField = FieldSpec.builder(Moshi.class, "moshi", PRIVATE, FINAL).build();
```
Comment (JakeWharton) [inline src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java]: I think this becomes unused now. Unless I'm not seeing it.

**Comment by JakeWharton** [comment]
LGTM. Perf win :+1:
